name: A workflow for my Hlloe World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      env:  
        MY_NAME: "Mona"
